# Generated by Django 5.2.3 on 2025-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
