# Generated by Django 5.2.5 on 2025-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_pro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pro_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
